### PR TITLE
Fix library build issues and test on MacOS

### LINKED ISSUE #302: Basic Install instructions for wgrib2 3.5 on MacOS- Error with LD symbols and libwgrib2.dir  libwgrib2.dylib
I'm running into problems installing wgrib2 3.5 on MacOS (Intel).  I've placed the downloaded wgrib2 folder in my /usr/local directory. 

I have gcc-14, gfortran and cmake installed via Homebrew.

As is the case with current wgrib2 3.1.3, clang doesn't work so I'm forcing the use of gcc with these instructions
sudo cmake -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++

Here's the entire sequence of commands I'm running to try to install wgrib2 3.5—
 
```
cd /usr/local/wgrib2

mkdir build && cd build
sudo cmake -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ .. DCMAKE_INSTALL_PREFIX=install -DCMAKE_PREFIX_PATH=/usr/local/bin
make
make install

```
It attempts to build, gets to 99% then shows these errors:

**ld: symbol(s) not found for architecture x86_64
cc: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [wgrib2/libwgrib2.dylib] Error 1
make[1]: *** [wgrib2/CMakeFiles/wgrib2_lib.dir/all] Error 2
make: *** [all] Error 2**

The error seems to be around the file libwgrib2.dylib, wgrib2_lib.dir and ld symbols not found.

Can wgrib2 3.5 be installed on MacOS?

Any help and suggestions about  (1) correct directory to install and (2) additional dependency libraries that need to installed via Homebrew would be appreciated.  

Thank you in advance.

### LINKED ISSUE #312: wgrib 3.5.0 does not compile with apple-clang 14.0.3 on macOS
See https://github.com/JCSDA/spack-stack/actions/runs/13072810448/job/36477973444?pr=1486:

```
==> Installing wgrib2-3.5.0-gqrmyiw3bty42z3ivllqna2wasrh4d56 [88/327]
==> No binary for wgrib2-3.5.0-gqrmyiw3bty42z3ivllqna2wasrh4d56 found: installing from source
==> Fetching file:///Users/ec2-user/spack-stack/source-cache/_source-cache/archive/b2/b27b48228442a08bddc3d511d0c6335afca47252ae9f0e41ef6948f804afa3a1.tar.gz
==> No patches needed for wgrib2
==> wgrib2: Executing phase: 'cmake'
==> wgrib2: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    '/Users/ec2-user/spack-stack/CI/actions-runner/_work/spack-stack/spack-stack/envs/ue-apple-clang-14.0.3-buildcache/install/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder/apple-clang/14.0.3/gmake-4.2.1-xag2vei/bin/make' '-j8'

5 errors found in build log:
     2225    cd /Users/ec2-user/spack-stack/CI/actions-runner/_work/spack-stack
             /spack-stack/cache/build_stage/spack-stage-wgrib2-3.5.0-gqrmyiw3bt
             y42z3ivllqna2wasrh4d56/spack-build-gqrmyiw/wgrib2 && /opt/homebrew
             /Cellar/cmake/3.27.6/bin/cmake -E cmake_link_script CMakeFiles/wgr
             ib2_exe.dir/link.txt --verbose=1
     2226    /Users/ec2-user/spack-stack/CI/actions-runner/_work/spack-stack/sp
             ack-stack/spack/lib/spack/env/clang/clang -O3 -DNDEBUG -arch arm64
              -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mm
             acosx-version-min=13.0 -Wl,-search_paths_first -Wl,-headerpad_max_
             install_names CMakeFiles/wgrib2_exe.dir/wgrib2_main.c.o gctpc/sour
             ir/save_string.c.o CMakeFiles/wgrib2_lib.dir/Scaling_0001.c.o CMak
             eFiles/wgrib2_lib.dir/Scan.c.o CMakeFiles/wgrib2_lib.dir/Sec0.c.o 
             CMakeFiles/wgrib2_lib.dir/Sec1.c.o CMakeFiles/wgrib2_lib.dir/Sec3.
             c.o CMakeFiles/wgrib2_lib.dir/sec3_grids.c.o CMakeFiles/wgrib2_lib
             .dir/Sec4.c.o CMakeFiles/wgrib2_lib.dir/Sec5.c.o CMakeFiles/wgrib2
             _lib.dir/Sec6.c.o CMakeFiles/wgrib2_lib.dir/Sec_len.c.o CMakeFiles
             /wgrib2_lib.dir/Set_byte.c.o CMakeFiles/wgrib2_lib.dir/Set_date.c.
             o CMakeFiles/wgrib2_lib.dir/Set_ensm_derived_fcst.c.o CMakeFiles/w
             grib2_lib.dir/Set_ens_num.c.o CMakeFiles/wgrib2_lib.dir/Set_ftime1
             .c.o CMakeFiles/wgrib2_lib.dir/Set_ftime2.c.o CMakeFiles/wgrib2_li
             b.dir/Set_ftime_mode.c.o CMakeFiles/wgrib2_lib.dir/Set_gds.c.o CMa
             keFiles/wgrib2_lib.dir/Set_metadata.c.o CMakeFiles/wgrib2_lib.dir/
             Set_pdt.c.o CMakeFiles/wgrib2_lib.dir/Set_percentile.c.o CMakeFile
             s/wgrib2_lib.dir/Set_prob.c.o CMakeFiles/wgrib2_lib.dir/Set_sec_si
             ze.c.o CMakeFiles/wgrib2_lib.dir/Set_ts_dates.c.o CMakeFiles/wgrib
             2_lib.dir/setup_user_gribtable.c.o CMakeFiles/wgrib2_lib.dir/Set_v
             al.c.o CMakeFiles/wgrib2_lib.dir/simple_pk.c.o CMakeFiles/wgrib2_l
             ib.dir/Small_grib.c.o CMakeFiles/wgrib2_lib.dir/space_view2ij.c.o 
             CMakeFiles/wgrib2_lib.dir/space_view.c.o CMakeFiles/wgrib2_lib.dir
             /SpatialProcessing.c.o CMakeFiles/wgrib2_lib.dir/Spectral_bands.c.
             o CMakeFiles/wgrib2_lib.dir/stagger.c.o CMakeFiles/wgrib2_lib.dir/
             Status.c.o CMakeFiles/wgrib2_lib.dir/string2time_unit.c.o CMakeFil
             es/wgrib2_lib.dir/Submsg_uv.c.o CMakeFiles/wgrib2_lib.dir/subtime.
             c.o CMakeFiles/wgrib2_lib.dir/Summary.c.o CMakeFiles/wgrib2_lib.di
             r/swap_buffer.c.o CMakeFiles/wgrib2_lib.dir/test_sec.c.o CMakeFile
             s/wgrib2_lib.dir/Tigge.c.o CMakeFiles/wgrib2_lib.dir/Time_processi
             ng.c.o CMakeFiles/wgrib2_lib.dir/Timer.c.o CMakeFiles/wgrib2_lib.d
             ir/Tosubmsg.c.o CMakeFiles/wgrib2_lib.dir/Type_reftime.c.o CMakeFi
             les/wgrib2_lib.dir/UDF.c.o CMakeFiles/wgrib2_lib.dir/Undefine.c.o 
             CMakeFiles/wgrib2_lib.dir/units.c.o CMakeFiles/wgrib2_lib.dir/Unix
             _time.c.o CMakeFiles/wgrib2_lib.dir/Unmerge_fcst.c.o CMakeFiles/wg
             rib2_lib.dir/unpk_0.c.o CMakeFiles/wgrib2_lib.dir/unpk.c.o CMakeFi
             les/wgrib2_lib.dir/unpk_complex.c.o CMakeFiles/wgrib2_lib.dir/unpk
             _run_length.c.o CMakeFiles/wgrib2_lib.dir/update_sec3.c.o CMakeFil
             es/wgrib2_lib.dir/update_sec4.c.o CMakeFiles/wgrib2_lib.dir/v1_v2_
             if.c.o CMakeFiles/wgrib2_lib.dir/VerfTime.c.o CMakeFiles/wgrib2_li
             b.dir/Warn_old_g2lib.c.o CMakeFiles/wgrib2_lib.dir/Waves.c.o CMake
             Files/wgrib2_lib.dir/wgrib2_api.c.o CMakeFiles/wgrib2_lib.dir/wgri
             b2.c.o CMakeFiles/wgrib2_lib.dir/Wind_dir.c.o CMakeFiles/wgrib2_li
             b.dir/Wind_speed.c.o CMakeFiles/wgrib2_lib.dir/Wind_uv.c.o CMakeFi
             les/wgrib2_lib.dir/Write_sec.c.o CMakeFiles/wgrib2_lib.dir/Wrt_gri
             b.c.o CMakeFiles/wgrib2_lib.dir/wrtieee.c.o CMakeFiles/wgrib2_lib.
             dir/wxtext.c.o
  >> 2231    Undefined symbols for architecture arm64:
     2232      "_aec_buffer_decode", referenced from:
     2233          _unpk_grib in unpk.c.o
     2234      "_aec_buffer_encode", referenced from:
     2235          _aec_grib_out in aec_pk.c.o
     2236      "_alberfor", referenced from:
     2237          _gctpc_get_latlon in Gctpc.c.o

     ...

     2311          _gctpc_ll2xy_init in gctpc_ll2xy.c.o
     2312      "_psinv", referenced from:
     2313          _gctpc_get_latlon in Gctpc.c.o
     2314      "_psinvint", referenced from:
     2315          _gctpc_get_latlon in Gctpc.c.o
     2316    ld: symbol(s) not found for architecture arm64
  >> 2317    clang: error: linker command failed with exit code 1 (use -v to se
             e invocation)
  >> 2318    make[2]: *** [wgrib2/CMakeFiles/wgrib2_lib.dir/build.make:3684: wg
             rib2/libwgrib2.dylib] Error 1
     2319    make[2]: Leaving directory '/Users/ec2-user/spack-stack/CI/actions
             -runner/_work/spack-stack/spack-stack/cache/build_stage/spack-stag
             e-wgrib2-3.5.0-gqrmyiw3bty42z3ivllqna2wasrh4d56/spack-build-gqrmyi
             w'
  >> 2320    make[1]: *** [CMakeFiles/Makefile2:977: wgrib2/CMakeFiles/wgrib2_l
             ib.dir/all] Error 2
     2321    make[1]: *** Waiting for unfinished jobs....
     2322    [100%] Built target wgrib2_exe
     2323    make[1]: Leaving directory '/Users/ec2-user/spack-stack/CI/actions
             -runner/_work/spack-stack/spack-stack/cache/build_stage/spack-stag
             e-wgrib2-3.5.0-gqrmyiw3bty42z3ivllqna2wasrh4d56/spack-build-gqrmyi
             w'
  >> 2324    make: *** [Makefile:149: all] Error 2
```

### PR DESCRIPTION
**Pull request by AlysonStahl-NOAA**
Part of #320 
Fixes #312 
Fixes #302

### CODE REVIEW

**Comment by AlysonStahl-NOAA** [comment]
So I believe I fixed the issue with the library build.

I'm having trouble getting the Windows workflow to work, even for a completely bare bones version of wgrib2 (most build options off).

From other discussions / issues it sounds like some  changes are required to compile wgrib2 on some newer systems / compilers.

I will remove the Windows workflow for now so I can merge these changes and release 3.6

**Comment by webisu** [comment]
The pre-github version of wgrib2 only used the integer types:
      int, long int and size_t.
With the new version of wgrib2, the integer types are
     int, long int, long long int, size_t and int64_t

On all windows compilers except for cygwin, long int is 32 bits.
So it is possible that some type changes could fail.

The default wgrib2 uses Posix 2 extensions.  This is fine with
the cygwin compiler which is Posix compliant.  Other Windows
compilers are not Posix 2 compliant and will have to have options
turned off.  Removing Posix features from the default wgrib2 build
would eliminate the regex library and produce something that nobody would
use.  Some windows compilers include the regex library. For compilers
that don't include the regex library, I have suggested that they
install the gnu regex library.

**Comment by climbfuji** [comment]
May I ask what the status of this PR is, and when the new release will be available to us for inclusion in spack-stack? Thanks!

**Comment by AlysonStahl-NOAA** [comment]
I will do a release once these changes are merged. This PR is just waiting for a careful review. Apologies for the delay, I had forgotten Monday was a holiday so my requests for review probably haven't been seen yet.

**Review by edwardhartnett — APPROVED** [review]

File: tests/test_lib.sh [hunk 1]
```diff
@@ -6,7 +6,7 @@
 echo "see if shared library made"
 set -xe
 
-if [ ! -f ../wgrib2/libwgrib2.so -a ! -f ../wgrib2/libwgrib2.a ] ; then
+if [ ! -f ../wgrib2/libwgrib2.so -a ! -f ../wgrib2/libwgrib2.a  &&  ! -f ../wgrib2/libwgrib2.dylib ] ; then
```
Comment (AlexanderRichert-NOAA) [inline tests/test_lib.sh]: At least in bash, using the && in an if condition requires double square brackets. Testing this on my personal machine gives 'bash: [: missing `]'/' (same error if I use /bin/sh). Same for the change to test_shared_lib.sh.

Comment (AlysonStahl-NOAA) [reply tests/test_lib.sh]: Fixed
