### ISSUE TITLE
wgrib 3.5.0 does not compile with apple-clang 14.0.3 on macOS

### ISSUE THREAD

**Issue by climbfuji** [NOAA-EMC/wgrib2#312]
See https://github.com/JCSDA/spack-stack/actions/runs/13072810448/job/36477973444?pr=1486:

```
==> Installing wgrib2-3.5.0-gqrmyiw3bty42z3ivllqna2wasrh4d56 [88/327]
==> No binary for wgrib2-3.5.0-gqrmyiw3bty42z3ivllqna2wasrh4d56 found: installing from source
==> Fetching file:///Users/ec2-user/spack-stack/source-cache/_source-cache/archive/b2/b27b48228442a08bddc3d511d0c6335afca47252ae9f0e41ef6948f804afa3a1.tar.gz
==> No patches needed for wgrib2
==> wgrib2: Executing phase: 'cmake'
==> wgrib2: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    '/Users/ec2-user/spack-stack/CI/actions-runner/_work/spack-stack/spack-stack/envs/ue-apple-clang-14.0.3-buildcache/install/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder/apple-clang/14.0.3/gmake-4.2.1-xag2vei/bin/make' '-j8'

5 errors found in build log:
     2225    cd /Users/ec2-user/spack-stack/CI/actions-runner/_work/spack-stack
             /spack-stack/cache/build_stage/spack-stage-wgrib2-3.5.0-gqrmyiw3bt
             y42z3ivllqna2wasrh4d56/spack-build-gqrmyiw/wgrib2 && /opt/homebrew
             /Cellar/cmake/3.27.6/bin/cmake -E cmake_link_script CMakeFiles/wgr
             ib2_exe.dir/link.txt --verbose=1
     2226    /Users/ec2-user/spack-stack/CI/actions-runner/_work/spack-stack/sp
             ack-stack/spack/lib/spack/env/clang/clang -O3 -DNDEBUG -arch arm64
              -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mm
             acosx-version-min=13.0 -Wl,-search_paths_first -Wl,-headerpad_max_
             install_names CMakeFiles/wgrib2_exe.dir/wgrib2_main.c.o gctpc/sour
             ir/save_string.c.o CMakeFiles/wgrib2_lib.dir/Scaling_0001.c.o CMak
             eFiles/wgrib2_lib.dir/Scan.c.o CMakeFiles/wgrib2_lib.dir/Sec0.c.o 
             CMakeFiles/wgrib2_lib.dir/Sec1.c.o CMakeFiles/wgrib2_lib.dir/Sec3.
             c.o CMakeFiles/wgrib2_lib.dir/sec3_grids.c.o CMakeFiles/wgrib2_lib
             .dir/Sec4.c.o CMakeFiles/wgrib2_lib.dir/Sec5.c.o CMakeFiles/wgrib2
             _lib.dir/Sec6.c.o CMakeFiles/wgrib2_lib.dir/Sec_len.c.o CMakeFiles
             /wgrib2_lib.dir/Set_byte.c.o CMakeFiles/wgrib2_lib.dir/Set_date.c.
             o CMakeFiles/wgrib2_lib.dir/Set_ensm_derived_fcst.c.o CMakeFiles/w
             grib2_lib.dir/Set_ens_num.c.o CMakeFiles/wgrib2_lib.dir/Set_ftime1
             .c.o CMakeFiles/wgrib2_lib.dir/Set_ftime2.c.o CMakeFiles/wgrib2_li
             b.dir/Set_ftime_mode.c.o CMakeFiles/wgrib2_lib.dir/Set_gds.c.o CMa
             keFiles/wgrib2_lib.dir/Set_metadata.c.o CMakeFiles/wgrib2_lib.dir/
             Set_pdt.c.o CMakeFiles/wgrib2_lib.dir/Set_percentile.c.o CMakeFile
             s/wgrib2_lib.dir/Set_prob.c.o CMakeFiles/wgrib2_lib.dir/Set_sec_si
             ze.c.o CMakeFiles/wgrib2_lib.dir/Set_ts_dates.c.o CMakeFiles/wgrib
             2_lib.dir/setup_user_gribtable.c.o CMakeFiles/wgrib2_lib.dir/Set_v
             al.c.o CMakeFiles/wgrib2_lib.dir/simple_pk.c.o CMakeFiles/wgrib2_l
             ib.dir/Small_grib.c.o CMakeFiles/wgrib2_lib.dir/space_view2ij.c.o 
             CMakeFiles/wgrib2_lib.dir/space_view.c.o CMakeFiles/wgrib2_lib.dir
             /SpatialProcessing.c.o CMakeFiles/wgrib2_lib.dir/Spectral_bands.c.
             o CMakeFiles/wgrib2_lib.dir/stagger.c.o CMakeFiles/wgrib2_lib.dir/
             Status.c.o CMakeFiles/wgrib2_lib.dir/string2time_unit.c.o CMakeFil
             es/wgrib2_lib.dir/Submsg_uv.c.o CMakeFiles/wgrib2_lib.dir/subtime.
             c.o CMakeFiles/wgrib2_lib.dir/Summary.c.o CMakeFiles/wgrib2_lib.di
             r/swap_buffer.c.o CMakeFiles/wgrib2_lib.dir/test_sec.c.o CMakeFile
             s/wgrib2_lib.dir/Tigge.c.o CMakeFiles/wgrib2_lib.dir/Time_processi
             ng.c.o CMakeFiles/wgrib2_lib.dir/Timer.c.o CMakeFiles/wgrib2_lib.d
             ir/Tosubmsg.c.o CMakeFiles/wgrib2_lib.dir/Type_reftime.c.o CMakeFi
             les/wgrib2_lib.dir/UDF.c.o CMakeFiles/wgrib2_lib.dir/Undefine.c.o 
             CMakeFiles/wgrib2_lib.dir/units.c.o CMakeFiles/wgrib2_lib.dir/Unix
             _time.c.o CMakeFiles/wgrib2_lib.dir/Unmerge_fcst.c.o CMakeFiles/wg
             rib2_lib.dir/unpk_0.c.o CMakeFiles/wgrib2_lib.dir/unpk.c.o CMakeFi
             les/wgrib2_lib.dir/unpk_complex.c.o CMakeFiles/wgrib2_lib.dir/unpk
             _run_length.c.o CMakeFiles/wgrib2_lib.dir/update_sec3.c.o CMakeFil
             es/wgrib2_lib.dir/update_sec4.c.o CMakeFiles/wgrib2_lib.dir/v1_v2_
             if.c.o CMakeFiles/wgrib2_lib.dir/VerfTime.c.o CMakeFiles/wgrib2_li
             b.dir/Warn_old_g2lib.c.o CMakeFiles/wgrib2_lib.dir/Waves.c.o CMake
             Files/wgrib2_lib.dir/wgrib2_api.c.o CMakeFiles/wgrib2_lib.dir/wgri
             b2.c.o CMakeFiles/wgrib2_lib.dir/Wind_dir.c.o CMakeFiles/wgrib2_li
             b.dir/Wind_speed.c.o CMakeFiles/wgrib2_lib.dir/Wind_uv.c.o CMakeFi
             les/wgrib2_lib.dir/Write_sec.c.o CMakeFiles/wgrib2_lib.dir/Wrt_gri
             b.c.o CMakeFiles/wgrib2_lib.dir/wrtieee.c.o CMakeFiles/wgrib2_lib.
             dir/wxtext.c.o
  >> 2231    Undefined symbols for architecture arm64:
     2232      "_aec_buffer_decode", referenced from:
     2233          _unpk_grib in unpk.c.o
     2234      "_aec_buffer_encode", referenced from:
     2235          _aec_grib_out in aec_pk.c.o
     2236      "_alberfor", referenced from:
     2237          _gctpc_get_latlon in Gctpc.c.o

     ...

     2311          _gctpc_ll2xy_init in gctpc_ll2xy.c.o
     2312      "_psinv", referenced from:
     2313          _gctpc_get_latlon in Gctpc.c.o
     2314      "_psinvint", referenced from:
     2315          _gctpc_get_latlon in Gctpc.c.o
     2316    ld: symbol(s) not found for architecture arm64
  >> 2317    clang: error: linker command failed with exit code 1 (use -v to se
             e invocation)
  >> 2318    make[2]: *** [wgrib2/CMakeFiles/wgrib2_lib.dir/build.make:3684: wg
             rib2/libwgrib2.dylib] Error 1
     2319    make[2]: Leaving directory '/Users/ec2-user/spack-stack/CI/actions
             -runner/_work/spack-stack/spack-stack/cache/build_stage/spack-stag
             e-wgrib2-3.5.0-gqrmyiw3bty42z3ivllqna2wasrh4d56/spack-build-gqrmyi
             w'
  >> 2320    make[1]: *** [CMakeFiles/Makefile2:977: wgrib2/CMakeFiles/wgrib2_l
             ib.dir/all] Error 2
     2321    make[1]: *** Waiting for unfinished jobs....
     2322    [100%] Built target wgrib2_exe
     2323    make[1]: Leaving directory '/Users/ec2-user/spack-stack/CI/actions
             -runner/_work/spack-stack/spack-stack/cache/build_stage/spack-stag
             e-wgrib2-3.5.0-gqrmyiw3bty42z3ivllqna2wasrh4d56/spack-build-gqrmyi
             w'
  >> 2324    make: *** [Makefile:149: all] Error 2
```

**Comment by climbfuji** [comment]
Note. wgrib2@3.4.0 builds on macOS with apple-clang@14.0.3. Thus. this (3.4.0) is what we use for spack-stack@1.9.0 on macOS, all other systems will use 3.5.0. There should be a conflict added to wgrib2 for 3.5.0 with certain macOS apple-clang compilers.

**Comment by AlysonStahl-NOAA** [comment]
I believe this will be fixed for version 3.6.0. The changes have been tested on MacOS.

I should have version 3.6.0 available soon (hopefully end of the day at the earliest, Monday at the latest).

**Comment by webisu** [comment]
C23 makes old-style prototypes illegal.  This was noticed
by github issues: clang compile problems, and gcc v15 compile
problems.  This problem may apply to newer versions of apple clang.

I have finished adding prototypes to wgrib2 and I was waiting for
the python lib pull request to go through before trying to
submit a pull request.

Has the problem with openjpeg been addressed?  This same
problem should also apply to the Jasper decoder.
